# Any language can be specified, the ghdl scripts not depend any of them.
# (Default language is ruby on travis)
language: python

# Specify, that we want to use docker in the docker :)
services:
  - docker

before_install:
- docker ps -a

# Here are the list of run scripts of different DUTs/testcases
script:
# Testing the installation of the ghdl
- docker run -t ghdl/ghdl:buster-mcode ghdl --version
  
# Mount the repo to docker, and run the hello world example
- > 
  docker run -t -v `pwd`:/mnt/data ghdl/ghdl:buster-mcode
  ghdl --version
  ghdl -a /mnt/data/project.vhd
  
# Notification is optional
notifications:
  email:
    on_success: never
    on_failure: always
